name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: textbook/take-action@nodejs
      with:
        node-version: 20
    - name: Test 🧪
      run: |
        npm run lint
        npm test
        npm run e2e
      env:
        FORCE_COLOR: true
    - name: Deploy 🚀
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npx gh-pages --dist build --user 'github-actions-bot <support+actions@github.com>'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
