name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
      pages: write
    steps:
    - uses: textbook/take-action@nodejs
      with:
        node-version: 22
    - name: Test 🧪
      run: |
        npm run lint
        npm test -- --coverage
        npm run e2e
      env:
        FORCE_COLOR: true
    - name: Upload 📦
      uses: actions/upload-pages-artifact@v3
      with:
        path: build/
    - name: Deploy 🚀
      uses: actions/deploy-pages@v4
