name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        cache: 'npm'
    - name: Install 📦
      run: npm ci
    - name: Test 🧪
      run: |
        npm run lint
        npm test
        npm run e2e
    - name: Build 🛠
      run: npm run build
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: build
